services:
  backend:
    build: .
    container_name: tarisocial-backend-copy
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    container_name: tarisocial-frontend-copy
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
